apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mail-operator-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mail-operator-component
    app.kubernetes.io/part-of: mail-operator-app
  name: mail-operator-component
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: mail-operator-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mail-operator-component
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/managed-release-team-tenant/mail-operator-app/mail-operator-component@sha256:8479af819fb726ff0e55ab79a77ecc496348f429104ac72bc6534ec3efa2ee37
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
